##############################################################################
##
##  Tenio - VFS
##

DLL_NAME = vfs

RELATIVE_PATH   = ../..
MYPROJECT_HEADERS = "vfs.h" "Buffer.h" "BufferCache.h" "FileMapper.h" "FileSys.h" "FileSysMgr.h" "HandleAlloc.h" "VFileSys.h" "VFS.h" "ZlibFilter.h"
MYPROJECT_FILES   =  "VFS.cpp" "Buffer.cpp" "BufferCache.cpp" "FileMapper.cpp" "FileSys.cpp" "FileSysMgr.cpp" "HandleAlloc.cpp" "VFileSys.cpp" "VFS.cpp" "ZlibFilter.cpp"
USER_INCLUDE_PATH = "/I../../Include/VFS"

include "../../DLLMake/Makefile"

################################################################# End of File.
