#ifndef __NETWORKDEF_H__
#define __NETWORKDEF_H__

#define QQLO_MAXPROXYHOSTLEN		128
#define QQLO_MAXPROXYUSERNAMELEN	128
#define QQLO_MAXPROXYPASSWORDLEN	128
#define QQLO_MAXPROXYDOMAINLEN		128

typedef enum enumNETWORKPROXYTYPE
{
	EPT_NOTSET      = 0,
	EPT_SOCKS5PROXY = 1,
	EPT_HTTPPROXY   = 2
}ENUMNETWORKPROXYTYPE;

typedef struct _tagGLOBALNETWORKPROXYSETTING
{
	USHORT ushStructSize;
	
	BOOL bUseProxy;
	ENUMNETWORKPROXYTYPE nProxyType;
	
	USHORT ushProxyPort;
	TCHAR szProxyHost[QQLO_MAXPROXYHOSTLEN];
	TCHAR szProxyUserName[QQLO_MAXPROXYUSERNAMELEN];
	TCHAR szProxyPassword[QQLO_MAXPROXYPASSWORDLEN];
	TCHAR szProxyDomain[QQLO_MAXPROXYDOMAINLEN];
	
}GLOBALNETWORKPROXYSETTING, *PGLOBALNETWORKPROXYSETTING;


#endif